language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install -r requirements_dev.txt
  - pip install coveralls
  - pip install -e .

script:
  - flake8
  - nosetests --with-cover

after_success:
  - coveralls
